In [1]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import hamming_loss
import csv
import itertools
from random import shuffle
import numpy

In [2]:
# Random shuffle of data
link='dataset.csv'
with open(link, newline='', encoding='utf8') as f:
    data = f.readlines()
header = data[0]
rest = data[1:]
shuffle(rest)
temp_link='temp_preprocessed_data.csv'
with open(temp_link, 'w') as out:
    out.write(''.join([header]+rest))

In [3]:
# Removing empty rows

shuffle_link='shuffled_preprocessed_data.csv'

input1 = open(temp_link, 'r')
output1 = open(shuffle_link, 'w')

reader = csv.reader(input1)
writer = csv.writer(output1)

for line in input1.readlines():
    if line.strip()=='':
        continue
    output1.write(line)

input1.close()
output1.close()

In [4]:
# Splitting data into training and testing sets

link='shuffled_preprocessed_data.csv'

input1 = open(link, 'r')

lines = itertools.islice(input1,1,None)
reader = csv.reader(lines)

full_len = len(list(reader))
thres = int((full_len*95)/100)
print(thres)

input1.close()
              
with open(link, newline='', encoding='utf8') as f:
    cnt=0
    X_arr=[]
    X_test_arr=[]
    
    y_train_text=[]
    Y_test=[]
    
    lines = itertools.islice(f,1,None)
    reader = csv.reader(lines)
    
    for row in reader:
        if(cnt<thres):
            X_arr.append(row[1]+', '+row[2])
            list1=[]
            for i in range(5,len(row)):
                list1.append(row[i])
                
            y_train_text.append(list1)
        else:
            X_test_arr.append(row[1]+', '+row[2])
            list1=[]
            for i in range(5,len(row)):
                list1.append(row[i])
            Y_test.append(list1)
        
        cnt=cnt+1
        
    X_train = np.array(X_arr)
    X_test = np.array(X_test_arr)
    print(len(Y_test))
    print(Y_test)

5678
299
[['cinema', 'trailer', 'official', 'movie', 'ready official trailer', 'samara weaving', 'fear movie'], ['frog', 'rainbow', 'connection', 'comedy', 'good', 'movie', 'swamp', 'banjo', 'aerial', 'look', 'jim'], ['dancer', 'dark', 'trailer', 'movie', 'official', 'dance dark', 'lars trier', 'david morse', 'catherine', 'danish', 'palm', 'movie festival'], ['awful', 'awful movie', 'awful clip', 'awful scene', 'awful compilation', 'clip', 'scene', 'compilation', 'trailer', 'chloe bennet', 'albert', 'pearl', 'animation', 'fandango', 'family'], ['help', 'future', 'de', 'time', 'machine', 'scene', 'first', 'move', 'testing', 'experiment', 'temporal', 'shopping', 'mall', 'twin', 'trilogy', 'trailer', 'new'], ['movie clip', 'danish girl', 'danish girl movie', 'danish girl trailer', 'tom hooper', 'oscar movie', 'best leading actor nominee', 'best supporting actress nominee', 'best costume plan nominee', 'best production plan nominee', 'school award nominee'], ['vinyl collection', 'adam mart

In [5]:
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(y_train_text)

In [35]:
print(Y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
classifier = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', OneVsRestClassifier(LinearSVC()))])

In [7]:
classifier.fit(X_train, Y)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 OneVsRestClassifier(estimator=LinearSVC(C=1.0,
                                                         class_weight=None,
       

In [37]:
print(X_train)

['sonic the hedgehog new official trailer paramount, sonic the hedgehog is speeding to for a big hide adventure for the whole family look the new trailer now and in february based on the international blockbuster franchise from sonic the hedgehog the story of the international s hedgehog as he his new home on earth in this live action adventure comedy sonic and his new best friend tom james team up to defend the planet from the ugly genius jim and his for international domination the family good movie also sumpter and ben as the inform of sonic corporation a major international producer and distributor of entertainment is a unit of via home to premier international media that make compelling television motion short make inform consumer social media and other entertainment inform for in more than connect with paramount official place'
 'mile end delicatessen, another for this episode we head to mile stop delicatessen to sample their interpretation of style jewish cuisine then noah and c

In [36]:
predicted = classifier.predict(X_test)
print(predicted)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
text_labels = mlb.inverse_transform(predicted)

In [ ]:
# Storing all the predicted labels

test_data=[]
all_predicted_labels=[]
#temp_list=[]

for actual_text, predict_labels in zip(Y_test, text_labels):
    
    all_predicted_labels.append(predict_labels)
    
    if predict_labels:
        #print(predict_labels)
        
        test_data.append(actual_text)

#print(len(test_data))
print(all_predicted_labels)

In [ ]:
#print(test_data)

In [ ]:
Y_new = mlb.fit_transform(Y_test)
#print(Y_new)
#Y_new = mlb.fit_transform(test_data)

In [44]:
Y.shape

(5678, 19368)

In [46]:
predicted.shape

(299, 19368)

In [30]:
read_link='shuffled_preprocessed_data.csv'

# Header
list1=['Id', 'Title', 'Description', 'LikeCount', 'DislikeCount', 'Predicted Tags (comma delimited string)']
tot_list=[]
tot_list.append(list1)

with open(read_link, newline='', encoding='utf8') as f:
    lines = itertools.islice(f,1+thres,None)
    reader = csv.reader(lines)
    
    row_num=0
    for row in reader:
        #print(row)
        list2=[]
        for i in range(0,5):
            list2.append(row[i])
        list2.extend(all_predicted_labels[row_num])
        #print(list2)
        tot_list.append(list2)
        row_num+=1
    #print(tot_list)
f.close()

In [31]:
# Writing to file the predicted labels

write_link='predicted_data.csv'

with open(write_link, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(tot_list)

In [34]:
print(text_labels)

[('cinema', 'fear movie', 'movie', 'official', 'ready official trailer', 'samara weaving', 'trailer'), (), (), ('family',), (), ('movie clip', 'trailer'), (), (), ('drama', 'movie clip', 'official', 'thriller', 'trailer'), ('movie clip', 'official', 'trailer'), (), (), (), ('angela yee', 'breakfast club', 'celebrity news', 'envy', 'interview', 'radio', 'video'), ('donald glover', 'james earl jones', 'john oliver', 'lion king', 'michael key', 'official trailer', 'trailer'), ('henry', 'killer', 'movie', 'portrait', 'serial'), (), (), (), ('farrow', 'rosemary baby'), ('comedy', 'irving', 'movie clip', 'racing times high', 'slow night'), ('actor', 'actress', 'classic', 'cult', 'director', 'foreign', 'independent', 'movie buff', 'movie lover'), ('astrology', 'scorpio'), ('bounty hunter', 'classic western', 'el el malo el', 'eli wallach', 'fat scene', 'movie ending', 'movie scene', 'right awful ugly', 'spaghetti western'), (), ('movie clip', 'movie scene', 'platoon ambush', 'platoon charlie 

In [57]:
read_link='shuffled_preprocessed_data.csv'

# Header
list1=['Id', 'Title', 'Description', 'LikeCount', 'DislikeCount', 'Predicted Tags (comma delimited string)']
tot_list=[]
tot_list.append(list1)

acc=0
count_acc=0
real_acc=0
real_acc1=0
real_acc2=0
count_num=0

        
check_see=0
num_list=[]

for i in range(0,len(Y_test)):
    if (text_labels[i]):

        #print(str(Y_test[i])+"---->"+str(text_labels[i]))

        if len(set(Y_test[i]))!=0:
            recall=(len(set(Y_test[i]) & set(text_labels[i])))/(len(set(Y_test[i])))
        #real_acc+=recall

        if len(set(text_labels[i]))!=0:
            precision=(len(set(Y_test[i]) & set(text_labels[i])))/(len(set(text_labels[i])))
        #real_acc1+=precision
        
        if precision+recall>0:
            
            real_acc1+=precision
            real_acc+=recall
            
            f1_score=2*float((precision*recall)/(precision+recall))
            print(f1_score)
            real_acc2+=f1_score
            
            count_num+=1

            num_list.append(i)

num_list=np.array(num_list)
print(len(num_list))
print(num_list)

1.0
0.125
0.15384615384615385
0.5333333333333333
0.4615384615384615
0.7000000000000001
0.923076923076923
0.28571428571428575
0.9090909090909091
0.5142857142857142
0.5
0.17391304347826086
1.0
1.0
1.0
0.15384615384615385
0.10526315789473684
0.7499999999999999
0.22222222222222224
0.5555555555555556
0.2666666666666667
0.4444444444444444
0.125
0.6666666666666666
0.2857142857142857
1.0
0.13333333333333333
0.631578947368421
0.761904761904762
0.25
0.8125
0.3076923076923077
0.13333333333333333
0.8333333333333333
0.9696969696969697
0.846153846153846
0.13333333333333333
1.0
0.2857142857142857
0.5
0.125
0.19999999999999998
1.0
0.923076923076923
0.2857142857142857
0.09523809523809523
1.0
0.5263157894736842
0.8
0.30769230769230765
0.15384615384615385
0.6666666666666666
0.5000000000000001
0.14285714285714288
0.5
1.0
1.0
0.16666666666666669
0.2222222222222222
0.8571428571428572
0.07142857142857142
0.7999999999999999
0.13333333333333333
0.7000000000000001
0.6666666666666666
0.18181818181818182
0.086956

0.2857142857142857


In [17]:
with open(read_link, newline='', encoding='utf8') as f:
    lines = itertools.islice(f,1+thres,None)
    reader = csv.reader(lines)

    row_num=0
    j=0
    for row in reader:
        if row_num==num_list[j]:
            #check_see+=1
            list2=[]
            for i in range(0,5):
                list2.append(row[i])
            list2.extend(all_predicted_labels[row_num])
            tot_list.append(list2)
            
            if j==len(num_list)-1:
                break;
            
            j+=1
        row_num+=1
    print(tot_list)
    

[['Id', 'Title', 'Description', 'LikeCount', 'DislikeCount', 'Predicted Tags (comma delimited string)'], ['AXeYU6Kmrek', 'ready or not official trailer samara weaving horror movie', 'ready or not official trailer samara weaving fear movie fox kids family and interesting movie blockbuster action cinema blockbuster movie or fantasy movie drama we put you in the know subscribe now to take the best movie and the latest official movie trailer movie clip scene review interview', '38350.0', '842.0', 'cinema', 'fear movie', 'movie', 'official', 'ready official trailer', 'samara weaving', 'trailer'], ['3aoTWBZ3GmY', 'abominable all clips fandango family', 'check out the all the clip and associated with the promotion of awful before it hit on september take to awful look more awful s movie little interesting movie clip on of gross the fandango family subscribe to family look love us on follow us on twitter follow us on family you get family good clip and that are perfect for all to have', '2002.

In [18]:
# Writing to file the predicted labels which rendered an output of at least 1 label

write_link='final_predicted_data.csv'

with open(write_link, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(tot_list)

In [19]:
read_link='final_predicted_data.csv'

clean_link='without_duplicates_final_predicted_data.csv'

# Removing duplicate rows from the data set
with open(read_link, 'r') as in_file, open(clean_link, 'w') as out_file:
    seen = set()
    for line in in_file:
        if line in seen: continue
            
        seen.add(line)
        out_file.write(line)

In [50]:
print(acc)
#print(count_acc)
#real_acc=acc/len(Y_test)
#curr_acc=acc/count_acc
avg_recall=real_acc/count_num
avg_precision=real_acc1/count_num
avg_f1_score=real_acc2/count_num
#print(len(test_data))
print(count_num)
#avg_precision1=real_acc1/count_num
#print(avg_precision1)
#print(check_see)

0
133


In [21]:
# Accuracy measures

# First accuracy is the recall value

# Second accuracy is the precision value

# Third accuracy is the f1 score which takes precision and recall values

print(avg_recall)
print(avg_precision)
print(avg_f1_score)

0.43696543941295596
0.8924284466577697
0.5100306795787977


In [65]:
print(len(Y_test))
print(len(test_data))

565
216


In [66]:
# Testing phase
'''
Y_test[0]=['news']
text_labels[0]=('news',' ')
Y_test[1]=['beautiful', 'cute', 'love', 'girl', 'comedy']
text_labels[1]=('beautiful', 'comedy', 'cute', 'girl', 'love')

Y_test[2]=['mobile']
text_labels[2]=('mobile', 'technical')
print(str(Y_test[1])+"---->"+str(text_labels[1]))
len(set(Y_test[2]) & set(text_labels[2]))/len(set(text_labels[2]))
'''

'\nY_test[0]=[\'news\']\ntext_labels[0]=(\'news\',\' \')\nY_test[1]=[\'beautiful\', \'cute\', \'love\', \'girl\', \'comedy\']\ntext_labels[1]=(\'beautiful\', \'comedy\', \'cute\', \'girl\', \'love\')\n\nY_test[2]=[\'mobile\']\ntext_labels[2]=(\'mobile\', \'technical\')\nprint(str(Y_test[1])+"---->"+str(text_labels[1]))\nlen(set(Y_test[2]) & set(text_labels[2]))/len(set(text_labels[2]))\n'